apiVersion: v1
kind: Pod
metadata:
  name: cloud-pod
  labels:
    app: self-hosted-cloud
spec:
  containers:
    # 1. Traefik Reverse Proxy
    - name: traefik
      image: traefik:latest
      args:
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.mytls.acme.httpchallenge=true"
        - "--certificatesresolvers.mytls.acme.httpchallenge.entrypoint=web"
        - "--certificatesresolvers.mytls.acme.email=admin@example.com"
        - "--certificatesresolvers.mytls.acme.storage=/letsencrypt/acme.json"
      ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
      volumeMounts:
        - name: traefik-config
          mountPath: /etc/traefik
        - name: traefik-letsencrypt
          mountPath: /letsencrypt
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532

    # 2. OpenResty
    - name: openresty
      image: openresty/openresty:latest
      labels:
        traefik.enable: "true"
        traefik.http.routers.openresty.rule: "Host(`openresty.example.com`)"
        traefik.http.routers.openresty.entrypoints: "websecure"
        traefik.http.routers.openresty.tls.certresolver: "mytls"
      volumeMounts:
        - name: openresty-config
          mountPath: /usr/local/openresty/nginx/conf

    # 3. Nextcloud
    - name: nextcloud
      image: nextcloud:latest
      env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_USER
          value: nextcloud
        - name: POSTGRES_PASSWORD
          value: ncpass
        - name: POSTGRES_DB
          value: nextcloud
        - name: REDIS_HOST
          value: redis
      labels:
        traefik.enable: "true"
        traefik.http.routers.nextcloud.rule: "Host(`nextcloud.example.com`)"
        traefik.http.routers.nextcloud.entrypoints: "websecure"
        traefik.http.routers.nextcloud.tls.certresolver: "mytls"
      volumeMounts:
        - name: nextcloud-data
          mountPath: /var/www/html

    # 4. AnythingLLM
    - name: anythingllm
      image: mintplexlabs/anythingllm:latest
      env:
        - name: DATABASE_URL
          value: postgres://llmuser:llmpass@postgres:5432/anythingllm
      labels:
        traefik.enable: "true"
        traefik.http.routers.anythingllm.rule: "Host(`llm.example.com`)"
        traefik.http.routers.anythingllm.entrypoints: "websecure"
        traefik.http.routers.anythingllm.tls.certresolver: "mytls"
      volumeMounts:
        - name: anythingllm-data
          mountPath: /app/data

    # 5. Grafana
    - name: grafana
      image: grafana/grafana:latest
      env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: grafanapass
      labels:
        traefik.enable: "true"
        traefik.http.routers.grafana.rule: "Host(`grafana.example.com`)"
        traefik.http.routers.grafana.entrypoints: "websecure"
        traefik.http.routers.grafana.tls.certresolver: "mytls"
      volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana

    # 6. n8n Automation
    - name: n8n
      image: n8nio/n8n:latest
      env:
        - name: DB_TYPE
          value: postgresdb
        - name: DB_POSTGRESDB_HOST
          value: postgres
        - name: DB_POSTGRESDB_PORT
          value: "5432"
        - name: DB_POSTGRESDB_DATABASE
          value: n8n
        - name: DB_POSTGRESDB_USER
          value: n8nuser
        - name: DB_POSTGRESDB_PASSWORD
          value: n8npass
        - name: QUEUE_BULL_REDIS_HOST
          value: redis
      labels:
        traefik.enable: "true"
        traefik.http.routers.n8n.rule: "Host(`n8n.example.com`)"
        traefik.http.routers.n8n.entrypoints: "websecure"
        traefik.http.routers.n8n.tls.certresolver: "mytls"
      volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n

    # 7. Wazuh
    - name: wazuh
      image: wazuh/wazuh:latest
      labels:
        traefik.enable: "true"
        traefik.http.routers.wazuh.rule: "Host(`wazuh.example.com`)"
        traefik.http.routers.wazuh.entrypoints: "websecure"
        traefik.http.routers.wazuh.tls.certresolver: "mytls"
      volumeMounts:
        - name: wazuh-data
          mountPath: /var/ossec/data

    # 8. PostgreSQL
    - name: postgres
      image: postgres:15
      env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: adminpass
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data

    # 9. Redis
    - name: redis
      image: redis:latest
      volumeMounts:
        - name: redis-data
          mountPath: /data

  volumes:
    - name: traefik-config
      hostPath:
        path: /data/traefik/config
    - name: traefik-letsencrypt
      hostPath:
        path: /data/traefik/letsencrypt
    - name: openresty-config
      hostPath:
        path: /data/openresty/config
    - name: nextcloud-data
      hostPath:
        path: /data/nextcloud
    - name: anythingllm-data
      hostPath:
        path: /data/anythingllm
    - name: grafana-data
      hostPath:
        path: /data/grafana
    - name: n8n-data
      hostPath:
        path: /data/n8n
    - name: wazuh-data
      hostPath:
        path: /data/wazuh
    - name: postgres-data
      hostPath:
        path: /data/postgres
    - name: redis-data
      hostPath:
        path: /data/redis